AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Disa: CFN Template to create am IAM Role for Lambda Function

Metadata:
  TemplateName: iam-role-stack.yaml
  TemplateType: IAM Role / IAM Policy
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Disa
  Modification History:
    - 1.0.0  - May 09, 2023   -- Initial Version 
  Resources: 
    - IAM Role
    - IAM Policy Attached To The Role
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: "Project And Environment:"
      Parameters: 
        - ProjectName
        - Environment
    #################################### KMS Key ###################################################
    - Label: 
        default: "KMS Configuration:"
      Parameters: 
      - KmsMasterKeyId
    #################################### Lambda Function ###########################################
    - Label:
        default: "Lambda Function:"
      Parameters:
      - LambdaFunctionCheckServiceBaseName
      - LambdaFunctionProcessBaseName
      - LambdaFunctionRetryBaseName
      - LambdaExecutionRoleName
      - LambdaExecutionPolicyName
    #################################### Step Function #############################################
    - Label:
        default: "Step Function:"
      Parameters:
      - StepFunctionExecutionRoleName
      - StepFunctionExecutionPolicyName
    #################################### EventBridge Scheduler #####################################
    - Label: 
        default: "Event Bridge Scheduler:"
      Parameters: 
      - EventBridgeSchedulerExecutionRoleName
      - EventBridgeSchedulerExecutionPolicyName
    #################################### DynamoDB Table ############################################
    - Label: 
        default: "DynamoDB Configuration:"
      Parameters: 
      - DynamoDBStreamArn
      - DynamoDBTableArn
    #################################### SNS Topic #################################################
    - Label: 
        default: "SNS Topic:"
      Parameters: 
        - SNSTopicBaseName
    #################################### CloudWatch Alarm ##########################################
    - Label: 
        default: "CloudWatch Alarm :"
      Parameters: 
        - CloudWatchAlarmArn
    ParameterLabels:
      ########################################### Project Name and Environment #######################
      ProjectName:
        default: "Project Name."
      Environment:
        default: "Environment Name."
      ################################## Lambda Function ###########################################
      LambdaFunctionCheckServiceBaseName: 
        default: "Processing Lammba Function Name."
      LambdaFunctionProcessBaseName: 
        default: "Processing Lammba Function Name."
      LambdaFunctionRetryBaseName:
        default: ""
      LambdaExecutionRoleName: 
        default: "Lambda Function Execution Role Name."
      LambdaExecutionPolicyName:
        default: "Lambda Function Execution Policy Name."
      ################################## Step Function #############################################
      StepFunctionExecutionRoleName: 
        default: "Step Function Execution Role Name."
      StepFunctionExecutionPolicyName: 
        default: "Step Function Execution Policy Name."
      ################################## EventBridge Scheduler #####################################
      EventBridgeSchedulerExecutionRoleName:
        default: "Event Bridge Scheduler Execution Role Name."
      EventBridgeSchedulerExecutionPolicyName:
        default: "Event Bridge Scheduler Execution Policy Name."
      ################################## DynamoDB Table ############################################
      DynamoDBStreamArn: 
        default: "DynamoDB Stream Arn."
      DynamoDBTableArn: 
        default: "DynamoDB Table Arn."
      ################################## SNS Topic #################################################
      SNSTopicBaseName:
        default: "SNS Topic Base Name."
      ################################## CloudWatch Alarm ##########################################
      CloudWatchAlarmArn:
        default: "CloudWatch Alarm Arn:"
Parameters:
  ################## Project Name and Environment ##################################################
  ProjectName:
    Default: disa
    Description: "The Project Name."
    Type: String
    MinLength: 4
    MaxLength: 30
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"
  ###################################### KMS #######################################################
  KmsMasterKeyId:
    Default: "e4c733c5-9fbe-4a90-bda1-6f0362bc9b89"
    Description: "The KMS Key Id Used For Encryption."
    Type: String
    MinLength: 36
    MaxLength: 36
    AllowedPattern: "[a-z0-9-]*"
    ConstraintDescription: "The length of the KMS Key Id should be 36 and must be lowercase alphabets, numbers and dash."
  ##################################### Lambda Function ###########################################
  LambdaFunctionCheckServiceBaseName:
    Default: some-lambda-function-name
    Description: Processing Lambda Function Name
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 10 and 40, must contain only alphanumeric or dash.
  LambdaFunctionProcessBaseName:
    Default: some-other-ambda-function-name
    Description: Processing Lambda Function Name
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 10 and 40, must contain only alphanumeric or dash.
  LambdaFunctionRetryBaseName:
    Default: some-other-ambda-function-name
    Description: Processing Lambda Function Name
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 10 and 40, must contain only alphanumeric or dash.
  LambdaExecutionRoleName:
    Default: lambda-function-role-name
    Description: Lambda Function Execution Role Name
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  LambdaExecutionPolicyName:
    Default: lambda-function-policy-name
    Description: Lambda Function Execution Policy Name
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  ###################################### Step Function #############################################
  StepFunctionExecutionRoleName:
    Default: Step-Function-Role-Name
    Description: Step Function Execution Role Name
    Type: String
    MinLength: 20
    MaxLength: 60
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  StepFunctionExecutionPolicyName:
    Default: Step-Function-Policy-Name
    Description: Step Function Execution Policy Name
    Type: String
    MinLength: 20
    MaxLength: 60
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  StepFunctionName:
    Default: step-function-name
    Description: Step Function Execution Policy Name
    Type: String
    MinLength: 5
    MaxLength: 50
    AllowedPattern: "[a-zA-Z-]*"
    ConstraintDescription: The length should be between 5 and 50, must contain only lowecase letters, numbers and hyphen (-).
  ###################################### EventBridge Scheduler #####################################
  EventBridgeSchedulerExecutionRoleName:
    Default: event-bridge-role
    Description: Event Bridge Scheduler Execution Role Name
    Type: String
    MinLength: 10
    MaxLength: 60
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  EventBridgeSchedulerExecutionPolicyName:
    Default: event-bridge-policy
    Description: Event Bridge Scheduler Execution Policy Name
    Type: String
    MinLength: 10
    MaxLength: 60
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only alphanumeric or dash.
  ###################################### DynamoDB Stream ###########################################
  DynamoDBStreamArn:
    Default: arn:aws:dynamodb:us-east-1:111111111111:table/dynamodb-table-name/stream/9999-12-31T00:00:00.000
    Description: "The Arn Of The DynamoDB Stream."
    Type: String
    MinLength: 20
    MaxLength: 200
    ConstraintDescription: "The length should be between 20 and 200, must contain only lowercase letter, number, dash and should start with a letter."
  DynamoDBTableArn:
    Default: arn:aws:dynamodb:us-east-1:111111111111:table/dynamodb-table-name
    Description: "The Arn Of The DynamoDB Table."
    Type: String
    MinLength: 20
    MaxLength: 200
    ConstraintDescription: "The length should be between 20 and 200, must contain only lowercase letter, number, dash and should start with a letter."
  DynamoDBTableGSIAttributeName:
    Default: sendStatus
    Description: "The Name Of The Dynamodb Partition Key."
    Type: String
    MinLength: 2
    MaxLength: 30
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9\-_]*'
    ConstraintDescription: "Must begin with a letter and contain only alphanumeric characters."
  ###################################### SNS Topic #################################################
  SNSTopicBaseName:
    Default: "carnation-sns-topic"
    Description: "The Base Name Of The Sns Topic. The Region And Environment Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length should be between 10 and 40, must contain only lowercase letter, number, dash, dot and should start with a letter."
  ###################################### CloudWatch Alarm ##########################################
  CloudWatchAlarmArn:
    Default: "cloudwatch-alarm-arn"
    Description: "The Base Name Of The Sqs Queue (Dead Letter Quque). The Region And Environment Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 20
    MaxLength: 200
    ConstraintDescription: "The length should be between 10 and 40, must contain only lowercase letter, number, dash, dot and should start with a letter."
Resources:
  ###################################### Lambda Execution Role #####################################
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref LambdaExecutionRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: !Ref LambdaExecutionPolicyName
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: AllowCloudWatchLogStream
              Effect: Allow
              Action: 
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: 
                - !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaFunctionCheckServiceBaseName}-${Environment}-${AWS::Region}:*'
                - !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaFunctionProcessBaseName}-${Environment}-${AWS::Region}:*'
                - !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaFunctionRetryBaseName}-${Environment}-${AWS::Region}:*'
            - Sid: AllowDynamoDBPutAndGetItem
              Effect: Allow
              Action: 
                - dynamodb:GetRecords
                - dynamodb:GetShardIterator
                - dynamodb:DescribeStream
                - dynamodb:ListStreams
                - dynamodb:UpdateItem
                - dynamodb:Query
              Resource: 
                - !Ref DynamoDBStreamArn
                - !Ref DynamoDBTableArn
                - !Sub '${DynamoDBTableArn}/index/GSI-${DynamoDBTableGSIAttributeName}'
            - Sid: AllowKMSDecrypt
              Effect: Allow
              Action: 
                - kms:Decrypt
                - kms:Encrypt
                - kms:GenerateDataKey
                - kms:GenerateDataKeyPair
              Resource: !Sub 'arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsMasterKeyId}'
            - Sid: AllowSNSPublishMessage
              Effect: Allow
              Action: 
                - sns:Publish
                - sns:GetTopicAttributes
              Resource: !Sub 'arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:${SNSTopicBaseName}-${Environment}-${AWS::Region}'
            - Sid: AllowCWPutMetricData
              Effect: Allow
              Action: 
                - cloudwatch:PutMetricData
              Resource: '*'
            - Sid: AllowStateMachineExecution
              Effect: Allow
              Action: 
                - states:StartExecution
              Resource: !Sub 'arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${StepFunctionName}-${Environment}-${AWS::Region}'
      Tags: 
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: EnvironmentName
          Value: !Ref Environment
  ###################################### Event Bridge Scheduler Execution Role #####################
  EventBridgeSchedulerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref EventBridgeSchedulerExecutionRoleName
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - scheduler.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: !Ref EventBridgeSchedulerExecutionPolicyName
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: AllowEventBridgeSchedulerExecution
              Effect: Allow
              Action: 
                - lambda:InvokeFunction
              Resource:  
                - !Sub 'arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaFunctionRetryBaseName}-${Environment}-${AWS::Region}*'
  ###################################### State Machine Execution Role ##############################
  StepFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref StepFunctionExecutionRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - states.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaRole"
      Policies:
        - PolicyName: !Ref StepFunctionExecutionPolicyName
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: AllowKMSEncryptDecrypt
              Effect: Allow
              Action: 
              - kms:Decrypt
              - kms:Encrypt
              - kms:GenerateDataKey
              - kms:GenerateDataKeyPair
              Resource: !Sub 'arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsMasterKeyId}'
            - Sid: AllowCloudWatchDescribeAlarm
              Effect: Allow
              Action:
              - cloudwatch:DescribeAlarms
              Resource: !Ref CloudWatchAlarmArn
            - Sid: AllowDynamoDBUpdateItem
              Effect: Allow
              Action:
              - dynamodb:UpdateItem
              Resource: !Ref DynamoDBTableArn
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: EnvironmentName
          Value: !Ref Environment
Outputs:
  LambdaExecutionRoleArn:
    Description: The Arn of the Lambda Execution Role
    Value: !GetAtt LambdaExecutionRole.Arn
  StepFunctionExecutionRoleArn:
    Description: The Arn of the Step Function Execution Role
    Value: !GetAtt StepFunctionExecutionRole.Arn
  EventBridgeSchedulerExecutionRoleArn:
    Description: The Arn of the Event Bridge Scheduler Execution Role
    Value: !Ref EventBridgeSchedulerExecutionRole
