AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Disa: CFN Template to create a Lambda Function. 

Metadata:
  TemplateName: lambda-function-stack.yaml
  TemplateType: Lambda Function.
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Disa
  Modification History:
    - 1.0.0  - May 09, 2023   -- Initial Version 
  Resources: 
    - Lambda Function
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: "Project And Environment:"
      Parameters: 
      - ProjectName
      - Environment
    #################################### Lambda Function ###########################################
    - Label:
        default: "Lambda Function Configuration:"
      Parameters: 
      - LambdaExecutionRoleArn
      - LambdaHandlerPath
      - LambdaFunctionTimeoutSecs
      - LambdaRuntime
      - LambdaFunctionMemory
      - LambdaFunctionCodeBucket
      - LambdaFunctionCodeKey
      - LambdaFunctionName
      - LambdaFunctionDescription
      - LambdaReservedConcurrency
    ################################## State Machine #############################################
    - Label: 
        default: "Step Function Configuration:"
      Parameters: 
      - StepFunctionName
    #################################### DynamoDB Table ############################################
    - Label:
        default: "DynamoDB Table:"
      Parameters: 
      - DynamoDBTableName
    #################################### SNS Topic #################################################
    - Label: 
        default: "SNS Topic:"
      Parameters: 
        - SNSTopicBaseName
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Project Name."
      ################################## Lambda Function ###########################################
      LambdaExecutionRoleArn: 
        default: "Lammba Function Execution Role Arn."
      LambdaHandlerPath: 
        default: "Lambda Handler Path."
      LambdaFunctionTimeoutSecs:
        default: "Lambda Function Timeout in Seconds."
      LambdaRuntime: 
        default: "Lambda Runtime."
      LambdaFunctionMemory:
        default: "Lambda Fuction Memory."
      LambdaFunctionCodeBucket: 
        default: "Lambda Function Code S3 Bucket."
      LambdaFunctionCodeKey: 
        default: "Lambda Function Code Zip File Key."
      LambdaFunctionName:
        default: "Name of the Lambda Function."
      LambdaFunctionDescription:
        default: "Lambda Function Description." 
      LambdaReservedConcurrency:
        default: "Lambda Reserved Concurrency."
      ################################## DynamoDB Table ############################################
      DynamoDBTableName: 
        default: "Target DynamoDB Table:"
      ################################## State Machine #############################################
      StepFunctionName:
        default: "Step Function Name:"
      ################################## SNS Topic #################################################
      SNSTopicBaseName:
        default: "SNS Topic Base Name."
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: disa
    Description: "The Project Name."
    Type: String
    MinLength: 4
    MaxLength: 30
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"
  ###################################### Lambda Function ###########################################
  LambdaExecutionRoleArn:
    Default: arn:aws:iam::111111111111:role/lambda-role
    Description: Lambda Execution Role Arn
    Type: String
    MinLength: 40
    MaxLength: 100
    AllowedPattern: "[a-zA-Z0-9-:/]*"
    ConstraintDescription: The length should be between 40 and 100, must contain only letters and should start with an uppercase letter.
  LambdaHandlerPath:
    Default: index.lambda_handler
    Description: Lambda Execution Path
    Type: String
    MinLength: 10
    MaxLength: 50
    AllowedPattern: "[a-zA-Z0-9_.]*"
    ConstraintDescription: Must be between 10 and 50 characters long and should be a valid handler path.
  LambdaRuntime:
    Default: python3.8
    Description: "Lambda Runtime (Python 3.7, 3.8 or 3.9)"
    Type: String
    AllowedValues: [python3.7 ,python3.8, python3.9]
    ConstraintDescription: "The Lambda runtime should be either Python 3.7, 3.8 or 3.9"
  LambdaFunctionTimeoutSecs:
    Default: 300
    Description: Lambda function timeout period in seconds.
    Type: Number
    MinValue: 3
    MaxValue: 900
    ConstraintDescription: The Lambda timeout period should be between 3 and 900 seconds.
  LambdaFunctionMemory:
    Default: 256
    Description: The Lambda Function Memory in MB.
    Type: Number
    MinValue: 128
    MaxValue: 10240
    ConstraintDescription: The Lambda Memory should be between 128 and 10240.
  LambdaFunctionCodeBucket:
    Default: code-bucket
    Description: The Source Code S3 Bucket Base Name
    Type: String
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: The length should be between 3 and 63, must contain only lowercase letter,numbers,dash, dot and should start with a letter.
  LambdaFunctionCodeKey:
    Default: function.zip
    Description: "The Source Code Zip File Name"
    Type: String
    MinLength: 10
    MaxLength: 100
    AllowedPattern: "[a-zA-Z0-9-/_.]*"
    ConstraintDescription: "The length should be between 10 and 100, must contain only lowercase letter,numbers,dash, dot, underscore"
  LambdaFunctionName:
    Default: processing-lambda
    Description: Lambda Function Name
    Type: String
    MinLength: 15
    MaxLength: 50
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 15 and 50, must contain only lowercase letters and dash(-) and should start with a letter.
  LambdaFunctionDescription:
    Default: The Lambda Function Description.
    Description: The Lambda Function Description
    Type: String
    MinLength: 30
    MaxLength: 200
    AllowedPattern: "^[A-Z][a-zA-Z0-9 .,]*$"
    ConstraintDescription: The length should be between 30 and 300, must contain only lowercase letters,space( ) and dot(.) and should start with an uppercase letter.
  LambdaReservedConcurrency:
    Default: 1
    Description: "Lambda Reserved Concurrency"
    Type: Number
    MinValue: 0
    MaxValue: 5
  ###################################### DynamoDB Table ############################################
  DynamoDBTableName:
    Default: dynamodb-table
    Description: "The Name Of The Dynamodb Table Used For Iterating Using Step Function Map State."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length should be between 10 and 40, must contain only lowercase letter, number, dash and should start with a letter."
  ###################################### CloudWatch Custom Metric ##################################
  MetricName:
    Default: custom-metric
    Description: "The CloudWatch Custom Metric."
    Type: String
    MinLength: 5
    MaxLength: 255
    AllowedPattern: '[a-zA-Z-]*'
    ConstraintDescription: Must be between 5 and 255 characters long and begin with a letter and can contain number or hyphen (-).
  DimensionName: 
    Default: custom-dimension
    Description: "The CloudWatch Custom Metric."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: '[a-zA-Z-]*'
    ConstraintDescription: Must be between 5 and 30 characters long and begin with a letter and can contain number or hyphen (-).
  DimensionValue:
    Default: some-value
    Description: "The CloudWatch Custom Metric."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: '[a-zA-Z-]*'
    ConstraintDescription: Must be between 5 and 30 characters long and begin with a letter and can contain number or hyphen (-).
  CloudWatchNameSpace:
    Default: disa/service-available
    Description: "The CloudWatch Custom Metric."
    Type: String
    MinLength: 15
    MaxLength: 30
    AllowedPattern: '[a-zA-Z-]*[/]*[a-zA-Z-]*'
    ConstraintDescription: Must be between 15 and 30 characters long and begin with a letter and can contain number or hyphen (-).
  ###################################### State Machine #############################################
  StepFunctionName:
    Default: step-function-name
    Description: "The Base Name The Step Function. The Region And Environment Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: '[a-zA-Z-]*'
    ConstraintDescription: "Must be between 5 and 255 characters long and begin with a letter and can contain number or hyphen (-)."
  ###################################### SNS Topic #################################################
  SNSTopicBaseName:
    Default: "carnation-sns-topic"
    Description: "The Base Name Of The Sns Topic. The Region And Environment Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length should be between 10 and 40, must contain only lowercase letter, number, dash, dot and should start with a letter."
Resources:
  ###################################### Lambda Function ###########################################
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: !Ref LambdaRuntime
      FunctionName: !Sub  '${LambdaFunctionName}-${Environment}-${AWS::Region}'
      Description: !Ref LambdaFunctionDescription
      Role: !Ref LambdaExecutionRoleArn
      Handler: !Ref LambdaHandlerPath
      Code:
        S3Bucket: !Ref LambdaFunctionCodeBucket
        S3Key: !Ref LambdaFunctionCodeKey
      Timeout: !Ref LambdaFunctionTimeoutSecs
      MemorySize: !Ref LambdaFunctionMemory
      ReservedConcurrentExecutions: !Ref LambdaReservedConcurrency
      TracingConfig:
        Mode: Active
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
          METRIC_NAME: !Ref MetricName
          DIMENSION_NAME: !Ref DimensionName
          DIMENSION_VALUE: !Ref DimensionValue
          CLOUD_WATCH_NAME_SPACE: !Ref CloudWatchNameSpace
          STEP_FUNCTION_ARN: !Sub "arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${StepFunctionName}-${Environment}-${AWS::Region}"
          SNS_TOPIC_ARN: !Sub "arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:${SNSTopicBaseName}-${Environment}-${AWS::Region}"
      Tags: 
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key:  Environment
          Value: !Ref Environment
Outputs:
  LambdaFunctionArn: 
    Description: The Arn of the Lambda Function
    Value: !GetAtt LambdaFunction.Arn
