AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Disa : CFN Template To Create A SNS Topic With SQS Queue Subscription. 

Metadata:
  TemplateName: sns-stack.yaml
  TemplateType: SNS Topic with Subscription
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Disa
  Modification History:
    - 1.0.0  - May 09, 2023   -- Initial Version 
  Resources: 
    - SNS Topic with SQS Queue subscription
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: "Project And Environment:"
      Parameters: 
      - ProjectName
      - Environment
    #################################### KMS #######################################################
    - Label: 
        default: "KMS Configuration:"
      Parameters: 
      - KmsMasterKeyAlias
    #################################### SNS Topic and Subscription Email ##########################
    - Label: 
        default: "SNS Configuration:"
      Parameters: 
      - SNSTopicBaseName
      - SNSTopicDisplayName
      - SubscriptionEmail
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "The Project Name."
      Environment:
        default: "Environment Name."
      ################################## KMS #######################################################
      KmsMasterKeyAlias: 
        default: "Kms Key Alias."
      ################################## SNS Topic and Subscription Email ##########################
      SNSTopicBaseName:
        default: "The SNS Topic Name."
      SNSTopicDisplayName:
        default: "The SNS Topic Display Name."
      SubscriptionEmail:
        default: "The Email To Subscribe To The SNS Topic."
Parameters:
  ############################################ Project Name and Environment #####################
  ProjectName:
    Default: project
    Description: "The Project Name."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"
  ###################################### KMS #######################################################
  KmsMasterKeyAlias:
    Default: "SB-KMS"
    Description: "The KMS Master Key Alias To Be Used For Server Side Encryption."
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: "The length of the KMS Key Alias should be beteen 5 and 20 and can only contain lowercase alphanumeric characters and dash."
  ###################################### SNS Topic and Subscription Email ##########################
  SNSTopicBaseName:
    Default: "sns-topic-name"
    Description: "The Base Name Of The Sns Topic."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length of SNS Topic base name should be between 10 and 40, must contain only lowercase letter, number, dash, dot and should start with a letter."
  SNSTopicDisplayName:
    Default: "SNS Topic Name For Sending Notification"
    Description: "The SNS Topic Display Name."
    Type: String
    MinLength: 30
    MaxLength: 200
    AllowedPattern: "[a-zA-Z0-9-. _]*"
    ConstraintDescription: "The length should be between 30 and 200, must alphanumeric character, space, dot dash or underscore."
  SubscriptionEmail:
    Default: "someone@email.com"
    Description: "The Subscription Email For The SNS Topic."
    Type: String
    MinLength: 10
    MaxLength: 100
    AllowedPattern: "[a-zA-Z0-9-.@_]*"
    ConstraintDescription: "The length should be between 10 and 100, must be a valid email id."
Resources:
  ############################################# SNS Topic #############################################
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: !Ref SNSTopicDisplayName
      TopicName: !Sub '${SNSTopicBaseName}-${Environment}-${AWS::Region}'
      KmsMasterKeyId: !Sub 'alias/${KmsMasterKeyAlias}'
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key:  Environment
          Value: !Ref Environment
  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: __default_statement_ID
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - SNS:GetTopicAttributes
              - SNS:SetTopicAttributes
              - SNS:AddPermission
              - SNS:RemovePermission
              - SNS:DeleteTopic
              - SNS:Subscribe
              - SNS:ListSubscriptionsByTopic
              - SNS:Publish
            Resource: !Ref SNSTopic
            Condition:
              StringEquals:
                AWS:SourceOwner: !Ref AWS::AccountId
      Topics:
        - Ref: SNSTopic
  ########################################## SNS Subscription #############################################
  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref SubscriptionEmail
      TopicArn: !Ref SNSTopic
Outputs:
  SNSTopicArn:
    Description: The Arn of the SNS Topic.
    Value: !Ref SNSTopic
  SNSSubscriptionArn:
    Description: The Arn of the SNS Subscription.
    Value: !Ref SNSSubscription
